### PR TITLE
Add ability to build locally

### PR DESCRIPTION
**Pull request by Fryguy**
@bdunne Please review.

### CODE REVIEW

**Comment by bdunne** [comment]
Do you want to add basic usage to the README?

**Comment by Fryguy** [comment]
Yeah, then it will be part of index.md also - you ok with that?

**Comment by bdunne** [comment]
Maybe we should add a DEVELOPER_README.md?

**Comment by Fryguy** [comment]
Or I can just make a proper README and copy the index instead of symlink

**Comment by Fryguy** [comment]
ohhhh even better - let's make a CONTRIBUTING.md

**Pull request merged**
